language: c
addons:
  ssh_known_hosts: tzurl.org
script:
    - wget http://www.iana.org/time-zones/repository/releases/tzdata$TZDATA_RELEASE.tar.gz
    - mkdir tzdata$TZDATA_RELEASE
    - cd tzdata$TZDATA_RELEASE
    - tar zxf ../tzdata$TZDATA_RELEASE.tar.gz
    - cd ..
    - make
after_success:
    - sh generate-zoneinfo.sh
    - sh upload.sh
